# Generated by Django 2.2.4 on 2019-08-20 13:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),

    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='[0-9]+[a-zA-Z]?[/0-9+]?')])),
                ('zip_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(10)])),
                ('weight', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('Waiting for deliverer', 'Waiting for deliverer'), ('In transit', 'In transit'), ('Closed', 'Closed')], default='Waiting for deliverer', max_length=30)),
                ('dimensions', models.CharField(choices=[('Fits in a shoebox', 'Fits in a shoebox'), ('Fits in a front seat of a car', 'Fits in a front seat of a car'), ('Fits in a back seat of a car', 'Fits in a back seat of a car'), ('Fits in a hatchback or SUV', 'Fits in a hatchback or SUV'), ('Fits in a pickup truck', 'Fits in a pickup truck')], default='Fits in a pickup truck', max_length=30)),
                ('isPaid', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('deliverer', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverer', to=settings.AUTH_USER_MODEL)),
                ('deliveryAddress', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='deliveryAddress', to='hansweb.Address')),
                ('pickupAddress', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='pickupAddress', to='hansweb.Address')),
            ],
        ),
    ]
