# Generated by Django 2.0.13 on 2019-06-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hansweb', '0006_auto_20190628_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dimensions',
            field=models.IntegerField(choices=[(0, 'Fits in a shoebox'), (1, 'Fits in a front seat of a car'), (2, 'Fits in a back seat of a car'), (3, 'Fits in a hatchback or SUV'), (4, 'Fits in a pickup truck')], default='Fits in a pickup truck', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'WAITING_FOR_DELIVERER'), (1, 'IN_TRANSIT'), (2, 'CLOSED')], default='WAITING_FOR_DELIVERER', max_length=1),
        ),
    ]
