# Generated by Django 2.0.13 on 2019-07-08 12:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hansweb', '0008_auto_20190628_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryAddress',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='deliveryAddress', to='hansweb.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='dimensions',
            field=models.CharField(choices=[('Fits in a shoebox', 'Fits in a shoebox'), ('Fits in a front seat of a car', 'Fits in a front seat of a car'), ('Fits in a back seat of a car', 'Fits in a back seat of a car'), ('Fits in a hatchback or SUV', 'Fits in a hatchback or SUV'), ('Fits in a pickup truck', 'Fits in a pickup truck')], default='Fits in a pickup truck', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='isPaid',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickupAddress',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='pickupAddress', to='hansweb.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting for deliverer', 'Waiting for deliverer'), ('In transit', 'In transit'), ('Closed', 'Closed')], default='Waiting for deliverer', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
