# Generated by Django 2.2.4 on 2019-10-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hansweb', '0002_auto_20191005_1450'),
        ('admin', '0004_auto_20191005_1453'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='User',
        ),
    ]
